### ISSUE TITLE
Cannot generate windows code

### ISSUE THREAD

**Issue by Q1984** [oddcod3/Phantom-Evasion#59]
[>] Generating code...

Traceback (most recent call last):
  File "phantom-evasion.py", line 402, in <module>
    CompleteMenu()
  File "phantom-evasion.py", line 125, in CompleteMenu
    Phantom_lib.ModuleLauncher(module_type)
  File "Setup/Phantom_lib.py", line 937, in ModuleLauncher
    LoadExecModule(M_type,ModOpt)
  File "Setup/Phantom_lib.py", line 566, in LoadExecModule
    RevTcpStager_C_windows(ModOpt)
  File "Modules/payloads/Meterpreter_ReverseTcpStager_C_windows.py", line 95, in RevTcpStager_C_windows
    Ret_code += WindowsDefend(ModOpt)
  File "Modules/payloads/auxiliar/usefull.py", line 658, in WindowsDefend
    Ret_code += "FARPROC " + NdcNTQIP + " = GetProcAddress(" + ModOpt["NtdllHandle"] + ",\"NtQueryInformationProcess\");\n"
KeyError: 'NtdllHandle'

Setup is completed.

OS: Kali
Python: 3

Thanks!

**Comment by oddcod3** [comment]
Thank you @Q1984  I just fixed that.

**Comment by Dramelac** [comment]
Hello

I still have the same error
```
[>] Generating code...

Traceback (most recent call last):
  File "/data/Phantom-Evasion/./phantom-evasion.py", line 402, in <module>
    CompleteMenu()
  File "/data/Phantom-Evasion/./phantom-evasion.py", line 125, in CompleteMenu
    Phantom_lib.ModuleLauncher(module_type)
  File "Setup/Phantom_lib.py", line 937, in ModuleLauncher
    LoadExecModule(M_type,ModOpt)
  File "Setup/Phantom_lib.py", line 551, in LoadExecModule
    BuildReflectiveLoader(ModOpt)
  File "Modules/payloads/BuildReflectiveLoader_C_windows.py", line 126, in BuildReflectiveLoader
    Ret_code += WindowsDefend(ModOpt)
  File "Modules/payloads/auxiliar/usefull.py", line 658, in WindowsDefend
    Ret_code += "FARPROC " + NdcNTQIP + " = GetProcAddress(" + ModOpt["NtdllHandle"] + ",\"NtQueryInformationProcess\");\n"
KeyError: 'NtdllHandle'
```

OS: Kali
Python: 3

Thanks for your help!
